version: '3.4'
services:
 mysql:
  image: mysql:5.7.24
  restart: always
  networks:
   - app
  labels:
   - 'traefik.enable=false'
  ports:
   - '3306:3306'
  env_file:
   - .env.development
  environment:
   GITLAB_TOKEN: ''
   GITLAB_DOMAIN: ''
   GITLAB_APP_ID: ''

networks:
 app:
  driver: bridge
 users:
  driver: bridge
 elk_elk:
  external: true
