version: '3.4'
services:
 backend:
  build: .
  image: cloudhost/backend_staging:0.0.2
  command: npm run start:staging
  labels:
   - 'traefik.enable=true' 
   - 'traefik.backend=cloudhost-API'
   - 'traefik.docker.network=traefik'
   - 'traefik.frontend.rule=Host:staging.cloudhost.hsrw.eu;PathPrefix:/api'
   - 'traefik.port=3000'
  extra_hosts:
   - 'git.hsrw.eu:10.2.16.53'
  volumes:
   - /var/run/docker.sock:/var/run/docker.sock:ro
  networks:
   - app
   - traefik
  depends_on:
   - mysql
 mysql:
  image: mysql:5.7.24
  restart: always
  networks:
   - app
  labels:
   - 'traefik.enable=false'
  ports:
   - '3306:3306'
  env_file:
   - .env.staging
  environment:
   GITLAB_TOKEN: ''
   GITLAB_DOMAIN: ''
   GITLAB_APP_ID: ''
  volumes:
   - mysqldata:/var/lib/mysql

networks:
  traefik:
    external: true
  app:
   driver: bridge

volumes:
  mysqldata:
