version: '3.4'
services:
 backend:
  build:
   context: .
   target: modules
  image: cloudhost/backend_development:0.0.1
  command: npm run dev
  labels:
   - 'traefik.enable=true'
   - 'traefik.backend=cloudhost-API'
   - 'traefik.docker.network=traefik'
   - 'traefik.frontend.rule=Host:cloudhost.localhost;PathPrefix:/api'
   - 'traefik.port=3000'
  volumes:
   - /var/run/docker.sock:/var/run/docker.sock:ro
   - .:/usr/app/backend/
   - /usr/app/frontend/node_modules
  tty: true
  networks:
   - app
   - traefik
  depends_on:
   - mysql
 mysql:
  image: mysql:5.7.24
  restart: always
  networks:
   - app
  labels:
   - 'traefik.enable=false'
  ports:
   - '3306:3306'
  env_file:
   - .env.development
  environment:
   GITLAB_TOKEN: ''
   GITLAB_DOMAIN: ''
   GITLAB_APP_ID: ''


networks:
  traefik:
   external: true
  app:
   driver: bridge