version: '3.4'
services:
 backend:
  build: .
  image: cloudhost/backend_production:latest
  command: npm run start
  networks:
   - app
  env_file:
   - .env
  depends_on:
   - mysql
  ports:
   - '3000:3000'
