components:
 responses:
  UnauthorizedError:
   description: Access token is missing or invalid
  BadRequest:
   description: Bad request

paths:
 /api/database:
  get:
   security:
    - bearerAuth: []
   description: Returns database connection string
   tags: [User]
   responses:
    200:
     description: Ok
     content:
      application/json:
       schema:
        type: object
        properties:
         connectionString:
          type: string
          description: The connection string
    401:
     $ref: '#/components/responses/UnauthorizedError'
    500:
     $ref: '#/components/responses/BadRequest'
  post:
   security:
    - bearerAuth: []
   description: Returns database connection string
   tags: [User]
   responses:
    200:
     description: Ok
     content:
      application/json:
       schema:
        type: object
        properties:
         connectionString:
          type: string
          description: The connection string
    401:
     $ref: '#/components/responses/UnauthorizedError'
    500:
     $ref: '#/components/responses/BadRequest'
  delete:
   security:
    - bearerAuth: []
   description: Returns database connection string
   tags: [User]
   responses:
    200:
     description: Ok
     content:
      application/json:
       schema:
        type: object
        properties:
         connectionString:
          type: string
          description: The connection string
    401:
     $ref: '#/components/responses/UnauthorizedError'
    500:
     $ref: '#/components/responses/BadRequest'
