version: '3.4'
services:
  elasticsearch:
    image: elasticsearch:6.5.4
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      # disable X-Pack
      # see https://www.elastic.co/guide/en/x-pack/current/xpack-settings.html
      #     https://www.elastic.co/guide/en/x-pack/current/installing-xpack.html#xpack-enabling
      xpack.security.enabled: "false"
      xpack.monitoring.enabled: "false"
      xpack.graph.enabled: "false"
      xpack.watcher.enabled: "false"
    ulimits:
        nofile:
           soft: 65536
           hard: 65536
    networks:
      - elk
    restart: always
    ports:
      - 9200:9200
      - 9300:9300

  kibana:
    image: kibana:6.5.4
    networks:
      - elk
    depends_on:
      - elasticsearch
    restart: always
    ports:
      - 5601:5601
    volumes:
      - ./kibana/config/:/usr/share/kibana/config    

networks:
  elk:
    driver: bridge
